"""initial

Revision ID: 033811814d9f
Revises: 0ea02f1c3873
Create Date: 2023-05-12 01:18:00.678383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033811814d9f'
down_revision = '0ea02f1c3873'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
