"""initial

Revision ID: 0caa8e34191c
Revises:
Create Date: 2023-04-27 11:42:36.265497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0caa8e34191c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
