"""initial

Revision ID: 0ea02f1c3873
Revises: 1e99b2f8cae2
Create Date: 2023-05-12 00:57:38.820286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea02f1c3873'
down_revision = '1e99b2f8cae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
