"""allnew

Revision ID: 25cec15e2c41
Revises: 945a1052a886
Create Date: 2023-05-12 12:55:23.202561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cec15e2c41'
down_revision = '945a1052a886'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
