"""try new migration

Revision ID: 5740c196c608
Revises: 0caa8e34191c
Create Date: 2023-05-22 11:28:51.439813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5740c196c608"
down_revision = "0caa8e34191c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trades", "pnl")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trades",
        sa.Column(
            "pnl", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
