"""new

Revision ID: 945a1052a886
Revises: 8c214c4a2153
Create Date: 2023-05-12 12:54:16.943403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945a1052a886'
down_revision = '8c214c4a2153'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
