"""new

Revision ID: c47a3b37c6a4
Revises: b72b48276553
Create Date: 2023-05-24 11:27:36.427296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c47a3b37c6a4"
down_revision = "b72b48276553"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trades", sa.Column("pnl", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trades", "pnl")
    # ### end Alembic commands ###
